### ISSUE TITLE
Support for animated WebP, FLIF, BPG, MNG images.

### ISSUE THREAD

**Issue by ghost** [qzb/is-animated#1]
Add support for 

- [WebP](https://en.wikipedia.org/wiki/WebP) (supported by modern web browsers)
- [FLIF (Free Lossless Image Format)](https://en.wikipedia.org/wiki/Free_Lossless_Image_Format) (a new format)
- [BPG (Better Portable Graphics)](https://en.wikipedia.org/wiki/Better_Portable_Graphics)
- [MNG (Multiple-image Network Graphics)](https://en.wikipedia.org/wiki/Multiple-image_Network_Graphics)

**Comment by qzb** [comment]
When I created this library, I choose to mark as animated only pictures which are rendered as ones by at least one of major browsers. This decision was dictated by discrepancies between GIF standard and its inconsistent implementation across browsers. Since only WebP meets these criteria, and vivaxy's PR is finally merged, I'm closing this issue.
